### ISSUE TITLE
Organization: choose a tool for schema creation

### ISSUE THREAD

**Issue by ElizavetaShavlova** [tritonJS826/sooner-or-later-2d#38]

**Comment by ElizavetaShavlova** [comment]
There is a need to choose a tool for schema creation instead of dia.

For example options:
1. **Lucidchart** (Web) - Best online flowchart maker for collaboration and Microsoft Visio compatibility
3. **Textografo** (Web) - Best text-based flowchart maker for quickly turning outlines into flowcharts
4. **Draw.io** (Web, Windows, Mac, Linux, ChromeOS): Best free flowchart maker that works across all platforms
6. **SmartDraw** (Web) - Best collection of diagramming templates in a web app
7. **Gliffy Diagram** (Web) - Best online flowchart and diagramming tool for beginners
8. **Cacoo** (Web) - Best diagramming software for making custom charts and graphs

**Comment by ElizavetaShavlova** [comment]
I propose to choose draw.io due to the following pros:
- free to use
- cross-platform
- has integration with GitHub, Google Drive, OneDrive, and other services
- user friendly interface

**Comment by tritonJS826** [comment]
OK. Thanks) drawio is a good software, lets use it
